avali@/config/routes.rb
Rails.application.routes.draw do
 
  get 'curso/new'

  resources :cursos do
    resources :disciplinas
  end

  resources :users
  get 'sign_in' => 'sessions#new' 
  post 'sign_in' => 'sessions#create' 
  delete 'sign_out' => 'sessions#destroy'
  root 'sessions#new'

  

end

avali@/app/models/curso.rb
class Curso < ActiveRecord::Base
	has_many :disciplinas
	validates :name, length: {maximum: 100}, uniqueness: {case_sensitive: false, message: "O Curso já possui cadastro!"}
	validates :faculdade, presence: true

	before_save { self.name = name.downcase }
end 

avali@/app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
	belongs_to :curso
	validates :name, length: {maximum: 100}
	validates :name_prof, presence: true
	validates :nota, presence: true
	validates :comment, presence: true

	before_save { self.name = name.downcase }
end

avali@/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :name, length: {maximum: 50} 
	validates :password, presence: true, length: {minimum: 6}
	VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
	validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false} 
	validates :curso, presence: true
	validates :faculdade, presence: true
	validates :idade, presence: true

	before_save { self.email = email.downcase }
end

avali@/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorize
  	unless logged_in?
  		redirect_to root_url
  	end
  end

  def correct_user?
  	@user = User.find(params[:id])
  	unless current_user == @user
  		redirect_to users_path
  	end
  end

end

avali@/app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :authorize, except: [:new, :create]
  def index
  	@cursos = Curso.all
  end
  def new
  	@curso = Curso.new
  end
  def create
		user = current_user
		@curso = Curso.new(user_params)
  		if @curso.save
  		    flash[:notice] =  "Curso cadastrado com sucesso" 
  			redirect_to user_path(user)
  		else 
  			render action: :new
  		end 
	end
	private
	def user_params
		params.require(:curso).permit(:name,:faculdade)
	end
end

avali@/app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :authorize, except: [:new, :create]
  def index
    @curso = Curso.find(params[:curso_id])
  	@disciplinas = @curso.disciplinas
  end
  def new
  	@disciplina = Disciplina.new
  end
  def show
  	@disciplina = Disciplina.find(params[:id])
  end
  def create
		user = current_user
    @curso = Curso.find(params[:curso_id])
		@disciplina = @curso.disciplinas.create(user_params)
  		if @disciplina.save
  		    flash[:notice] =  "Disciplina cadastrada com sucesso" 
  			redirect_to user_path(user)
  		else 
  			render action: :new
  		end 
	end

	private
	def user_params
		params.require(:disciplina).permit(:name,:name_prof,:nota,:comment)
	end
end

avali@/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, except: [:destroy]
  def create
  	@user = User.find_by(email: params[:session][:email].downcase)
  	if @user && @user.authenticate(params[:session][:password])
  		sign_in(@user)
        redirect_to current_user
  	else
  		render action: :new
  	end
  end 

  def destroy
  	sign_out
  	redirect_to root_url
  end
  def new
  end
end

avali@/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize, except: [:new, :create]
    before_action :correct_user?, only: [:edit, :update, :destroy]
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
  		if @user.save
  		    flash[:notice] =  "Usuário foi criado com sucesso" 
  			redirect_to @user
  		else 
  			render action: :new
  		end 
	end
	
	def show #Aqui é onde fica meu HOME
		@user = User.find(params[:id])
	end

	def edit
  		@user = User.find(params[:id])
  	end

	def update
	  	@user = User.find(params[:id])
	  	if @user.update_attributes(user_params)
	  		redirect_to users_path
	  	else
	  		render action: :edit
	  	end
  end

	def destroy
	  	@user = User.find(params[:id])
	  	@user.destroy
	  	sign_out
	  	redirect_to root_path
  	end
	private
	def user_params
		params.require(:user).permit(:email,:name,:idade,:faculdade,:curso,:password,:password_confirmation)
	end
end

avali@/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = User.new
  end
end

avali@/app/helpers/application_helper.rb
module ApplicationHelper
end

avali@/app/helpers/cursos_helper.rb
module CursosHelper
end

avali@/app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

avali@/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		session[:user_id] = @user.id		
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def block_access
		if current_user.present?
			redirect_to users_path
		end
	end

	def sign_out
		session.delete(:user_id)
		@current_user = nil
	end	

	def logged_in?
		!current_user.nil?
	end

end

avali@/app/helpers/users_helper.rb
module UsersHelper
end

avali@/app/helpers/welcome_helper.rb
module WelcomeHelper
end

avali@/app/views/cursos/index.html.erb
      	                    
                    <div class="row">
                        <div class="col-md-5 col-md-offset-3">
                        	<h3>Lista Cursos</h3>
                            <table class="table table-bordered">
                                <thead>
                                    <tr class="active">
                                        <th>#</th>
                                        <th>Nome </th>
                                        <th>Faculdade</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @cursos.each do |curso| %>
                                    <tr>
                                        <td><%= curso.id %></td>
                                        <td><%= link_to curso.name, curso_disciplinas_path(curso) %></td>
                                        <td><%= curso.faculdade %></td>
                                    </tr>
                                    <% end %>
                                </tbody>
                            </table>
                            <p>Novo Curso? <%= link_to "Cadastre aqui!", new_curso_path %></p>
                        </div>                       	
                    </div>                    
        

avali@/app/views/cursos/new.html.erb
                                
                    <div class="row">                        
                        <div class="col-md-6 col-md-offset-3">                            
                            <div class="form-box">
                                <div class="form-top">
                                    <div class="form-top-left">
                                        <h3>Cadastre o curso</h3>
                                        <p>Realize o cadastro</p>
                                    </div>
                                    <div class="form-top-right">
                                        <i class="fa fa-pencil"></i>
                                    </div>
                                </div>
                                <div class="form-bottom">
                                   <%= form_for @curso do |f| %> 
                                        <% if @curso.errors.any? %> 
                                        <div id="error_explanation"> 
                                            <div class="alert-error"> 
                                                O formulário contém <%= pluralize(@curso.errors.count, "erro") %>. 
                                            </div> 
                                            <ul> 
                                                <% @curso.errors.full_messages.each do |msg| %>                                              
                                                <li><%= msg %></li> 
                                                <% end %> 
                                            </ul> 
                                        </div>
                                        <% end %>
                                    <% end %>
                                    
                                    <%= form_for :curso, url: cursos_path do |f| %>
                                        <p>
                                            <%= f.label :nome %><br>
                                            <%= f.text_field :name %>
                                        </p>
                                        <p>
                                            <%= f.label :faculdade %><br>
                                            <%= f.text_field :faculdade %>
                                        </p>
                                        <p>
                                            <div class="actions"><%= f.submit "Cadastrar", class: 'btn'%></div>
                                        </p>
                                        <% end %>                           
                                </div>
                            </div>                            
                        </div>
                    </div>                    

avali@/app/views/disciplinas/index.html.erb
                    <div class="row">
                        <div class="col-md-5 col-md-offset-3">
                        	<h3>Lista das Disciplinas</h3>
                            <table class="table table-bordered">
                                <thead>
                                    <tr class="active">
                                        <th>#</th>
                                        <th>Nome </th>
                                        <th>Professor</th>
                                        <th>Nota</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @disciplinas.each do |disciplina| %>
                                    <tr>
                                        <td><%= disciplina.id %></td>
                                        <td><%= link_to disciplina.name, curso_disciplinas_path %></td>
                                        <td><%= disciplina.name_prof %></td>
                                        <td><%= disciplina.nota %></td> <!-- Na verdade aqui é para aparecer a média da avalição geral da disciplina -->
                                    </tr>
                                    <% end %>
                                </tbody>
                            </table>
                            <p>Nova Disciplina? <%= link_to "Cadastre aqui!", new_curso_disciplina_path %></p>
                        </div>                       	
                    </div>

avali@/app/views/disciplinas/new.html.erb
                                
                    <div class="row">                        
                        <div class="col-md-6 col-md-offset-3">                            
                            <div class="form-box">
                                <div class="form-top">
                                    <div class="form-top-left">
                                        <h3>Cadastre a Disciplina</h3>
                                        <p>Realize o cadastro</p>
                                    </div>
                                    <div class="form-top-right">
                                        <i class="fa fa-pencil"></i>
                                    </div>
                                </div>
                                <div class="form-bottom">
                                    
                                    <%= form_for :disciplina, url: curso_disciplinas_path do |f| %>
                                        <p>
                                            <%= f.label :nome_da_disciplina %><br>
                                            <%= f.text_field :name %>
                                        </p>
                                        <p>
                                            <%= f.label :professor %><br>
                                            <%= f.text_field :name_prof %>
                                        </p>
                                        <p>
                                            <%= f.label :nota %><br>
                                            <%= f.range_field(:nota , in: 0..10)%>
                                        </p>
                                        <p>
                                            <%= f.label :comentário %><br>
                                            <%= f.text_area :comment %>
                                        </p>
                                        <p>
                                            <div class="actions"><%= f.submit "Cadastrar", class: 'btn'%></div>
                                        </p>
                                        <% end %>                           
                                </div>
                            </div>                            
                        </div>
                    </div><br>                    

avali@/app/views/disciplinas/show.html.erb
                    <div class="row">
                        <div class="col-sm-5">
                        	<h3>Comentários sobre <%= @disciplina.name %></h3>
                            
                            
                                <p><%= @disciplina.comment %></p><br>
                            

                        </div>                       	
                    </div>

avali@/app/views/layouts/_header.html.erb
<div class="top-content">          
    <div class="inner-bg">
        <div class="container">
			<div class="row">
     			<div class="col-sm-8 col-sm-offset-2 text">
            		<h1>avali@</h1>                            
     			</div>
			</div>
			<div>
				<% if logged_in? %>
					<header> 
						<div> 
							<nav class='navbar navbar-default'>
								<div class="container-fuild">	 
									<ul class='nav navbar-nav'> 
											<li><%= link_to "Perfil", current_user %></li>
											<li><%= link_to "Cursos", cursos_path %></li>
											<li><%= link_to "Sobre", current_user %></li> 
											<li><%= link_to "Settings", edit_user_path(current_user) %></li>			
											<li> <%= link_to "Log out", sign_out_path, method: "delete" %> </li>  
									</ul>
								</div> 
							</nav> 
						</div> 
					</header>
				<% end %> 
			</div>
		</div>
	</div>
</div>

avali@/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all','data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/header' %>

<%= yield %>

<!-- Footer -->
<br>
<footer>
  	<div class="container">
  		<div class="row">        			
   			<div class="col-sm-8 col-sm-offset-2">
   				<div class="footer-border"></div>
       			<p>Made by Pedro Neto</p>
       		</div>    			
       	</div>
    </div>
</footer>

</body>
</html>

avali@/app/views/users/_cadastro.html.erb
                                
                    <div class="row">                        
                        <div class="col-md-5 col-md-offset-3">                            
                            <div class="form-box">
                                <div class="form-top">
                                    <div class="form-top-left">
                                        <h3>Cadastro</h3>
                                        <p>Realize o seu cadastro</p>
                                    </div>
                                    <div class="form-top-right">
                                        <i class="fa fa-pencil"></i>
                                    </div>
                                </div>
                                <div class="form-bottom">
                                   <%= form_for @user do |f| %> 
                                        <% if @user.errors.any? %> 
                                        <div id="error_explanation"> 
                                            <div class="alert-error"> 
                                                O formulário contém <%= pluralize(@user.errors.count, "erro") %>. 
                                            </div> 
                                            <ul> 
                                                <% @user.errors.full_messages.each do |msg| %>                                              
                                                <li><%= msg %></li> 
                                                <% end %> 
                                            </ul> 
                                        </div>
                                        <% end %>
                                    <% end %>
                                    
                                    <%= form_for :user, url: users_path do |f| %>
                                        <p>
                                            <%= f.label :nome %><br>
                                            <%= f.text_field :name %>
                                        </p>
                                        <p>
                                            <%= f.label :email %><br>
                                            <%= f.text_field :email %>
                                        </p>
                                        <p>
                                            <%= f.label :idade %><br>
                                            <%= f.text_field :idade %>
                                        </p>
                                        <p>
                                            <%= f.label :faculdade %><br>
                                            <%= f.text_field :faculdade %>
                                        </p>
                                        <p>
                                            <%= f.label :curso %><br>
                                            <%= f.text_field :curso %>
                                        </p>
                                        <p>
                                            <%= f.label :senha %><br>
                                            <%= f.password_field :password %>
                                        </p>
                                        <p>
                                            <%= f.label :confirma_senha %><br>
                                            <%= f.password_field :password_confirmation %>
                                        </p>
                                        <p>
                                            <div class="actions"><%= f.submit "Cadastrar", class: 'btn'%></div>
                                        </p>
                                        <% end %>                           
                                </div>
                            </div>                            
                        </div>
                    </div>                    

avali@/app/views/users/_login.html.erb
                    
                    <div class="row">
                        <center>
                            <div class="col-md-5 col-md-offset-3">  
                                <div class="form-box">
                                    <div class="form-top">
                                        <div class="form-top-left">
                                            <h3>Faça seu login</h3>
                                            <p>Entre com Email e Senha:</p>
                                        </div>
                                        <div class="form-top-right">
                                            <span class="fa fa-lock"></span>
                                        </div>
                                    </div>                                
                                    <div class="form-bottom">
                                        <%= form_for :session, url: sign_in_path, class: 'login-form' do |f| %>
                                            <p>
                                                <%= f.label :email %><br>
                                                <%= f.text_field :email, autofocus: true %>
                                            </p>
                                            <p>
                                                <%= f.label :password %><br>
                                                <%= f.password_field :password, autocomplete: "off" %>
                                            </p>
                                        
                                            <%= f.submit "Entrar", class: 'btn' %>
                        
                                        <% end %>
                                    </div>
                                </div>
                                <div class="new_user">
                                    <p>Novo usuario? <%= link_to "Cadastre-se agora!", new_user_path %></p>
                                </div>                         
                            </div>
                        </center>
                    </div>                             

avali@/app/views/users/edit.html.erb
<div class="row">                        
                        <div class="col-md-6 col-md-offset-3">                            
                            <div class="form-box">
                                <div class="form-top">
                                    <div class="form-top-left">
                                        <h3>Editar</h3>
                                        <p>Mude sua senha ou exclua sua conta</p>
                                    </div>
                                    <div class="form-top-right">
                                        <i class="fa fa-pencil"></i>
                                    </div>
                                </div>
                                <div class="form-bottom">
                                   <%= form_for @user do |f| %> 
                                        <% if @user.errors.any? %> 
                                        <div id="error_explanation"> 
                                            <div class="alert-error"> 
                                                O formulário contém <%= pluralize(@user.errors.count, "erro") %>. 
                                            </div> 
                                            <ul> 
                                                <% @user.errors.full_messages.each do |msg| %>                                              
                                                <li><%= msg %></li> 
                                                <% end %> 
                                            </ul> 
                                        </div>
                                        <% end %>

                                        <p>
                                            <%= f.label :senha %><br>
                                            <%= f.password_field :password %>
                                        </p>
                                        <p>
                                            <%= f.label :confirma_senha %><br>
                                            <%= f.password_field :password_confirmation %>
                                        </p>
                                        <p>
                                            <div class="actions"><%= f.submit "Editar", class: 'btn'%></div>
                                        </p>
                                    <% end %>                           
                                </div>
                            </div>                            
                        </div>
                    </div>

avali@/app/views/users/index.html.erb
               	                    
                    <div class="row">
                        <div class="col-sm-5">
                        	<h3>Informações do Usuário</h3>
                            <table class="table table-bordered">
                                <thead>
                                    <tr class="active">
                                        <th>#</th>
                                        <th>Nome </th>
                                        <th>Faculdade</th>                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @users.each do |user| %>
                                    <tr>
                                        <td><%= user.id %></td>
                                        <td><%= user.curso %></td>
                                        <td><%= user.faculdade %></td>
                                    </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>                       	
                    </div>                    
        

avali@/app/views/users/new.html.erb
<%= render 'cadastro' %>

avali@/app/views/users/show.html.erb
 <% if flash[:notice] %>
    <div class="notice"><h4><%= flash[:notice] %></h4></div>
  <% end %> 
                    <div class="row">
                        <div class="jumbotron">
                                <h1>Bem Vindo <%= @user.name %></h1>
                        </div>                   
                    </div>

avali@/app/views/welcome/index.html.erb
 <% if flash[:notice] %>
    <div class="notice"><h4><%= flash[:notice] %></h4></div>
  <% end %>
<%= render 'users/login' %>